name: 部署到GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# 设置GitHub Pages的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一次部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 构建
        run: npm run build
        
      - name: 确保资源目录存在
        run: |
          mkdir -p ./dist/icon
          mkdir -p ./dist/models
          
      - name: 复制静态资源
        run: |
          cp -R ./public/icon/* ./dist/icon/ || true
          cp -R ./public/models/* ./dist/models/ || true
          cp ./public/manifest.json ./dist/ || true
          cp ./public/sw.js ./dist/ || true
      
      - name: 设置Pages
        uses: actions/configure-pages@v3
        
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 